// <auto-generated />
using System;
using Crama_Dacia_ASP.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crama_Dacia_ASP.NET.Migrations
{
    [DbContext(typeof(Crama_Dacia_ASPNETContext))]
    partial class Crama_Dacia_ASPNETContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Soi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeSoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Soi");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Tip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeTip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tip");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Vin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("ProductieDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoiID")
                        .HasColumnType("int");

                    b.Property<string>("Sortiment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SoiID");

                    b.ToTable("Vin");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.VinTip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TipID")
                        .HasColumnType("int");

                    b.Property<int>("VinID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipID");

                    b.HasIndex("VinID");

                    b.ToTable("VinTip");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Vin", b =>
                {
                    b.HasOne("Crama_Dacia_ASP.NET.Models.Soi", "Soi")
                        .WithMany("Vinuri")
                        .HasForeignKey("SoiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soi");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.VinTip", b =>
                {
                    b.HasOne("Crama_Dacia_ASP.NET.Models.Tip", "Tip")
                        .WithMany("VinTipuri")
                        .HasForeignKey("TipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crama_Dacia_ASP.NET.Models.Vin", "Vin")
                        .WithMany("VinTipuri")
                        .HasForeignKey("VinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tip");

                    b.Navigation("Vin");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Soi", b =>
                {
                    b.Navigation("Vinuri");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Tip", b =>
                {
                    b.Navigation("VinTipuri");
                });

            modelBuilder.Entity("Crama_Dacia_ASP.NET.Models.Vin", b =>
                {
                    b.Navigation("VinTipuri");
                });
#pragma warning restore 612, 618
        }
    }
}
